services:
  - type: web
    name: mes-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        sync: false # Điền domain frontend Vercel của bạn trên dashboard của Render (vd: https://mes-app.vercel.app)
      - key: DATABASE_URL
        sync: false # Điền link Supabase của bạn vào đây trên dashboard
      - key: JWT_SECRET
        generateValue: true # Render sẽ tự động sinh mã bí mật an toàn
